# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20170712_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'article category',
                'verbose_name_plural': 'article categories',
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.AlterField(
            model_name='categoryrelation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_rel', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='wiki.Article'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='member_articles',
            field=models.ManyToManyField(blank=True, related_name='categories', to='wiki.Article'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wiki.ArticleCategory', verbose_name='parent'),
        ),
        migrations.AlterUniqueTogether(
            name='articlecategory',
            unique_together=set([('parent', 'name')]),
        ),
    ]
