# Generated by Django 2.1 on 2019-07-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_urlpath_moved_to'),
        ('wiki', '0003_auto_20170819_0708'),
    ]

    operations = [
    ]
