# Generated by Django 2.1.10 on 2019-07-10 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_merge_20190702_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrelation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
