# Generated by Django 3.1 on 2021-03-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_delete_category'),
        ('wiki', '0003_mptt_upgrade'),
    ]

    operations = [
    ]
