# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170208_1543'),
        ('wiki', '0002_auto_20170313_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='_article_categories_+', to='categories.Category'),
        ),
    ]
