# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20170327_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='categoryrelation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryrelation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryRelation',
        ),
    ]
