# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170217_1111'),
        ('wiki', '0005_auto_20170327_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='_article_categories_+', to='categories.Category'),
        ),
    ]
