# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 21:25
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_category_landing_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='landing_article',
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='xyz', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='alternate_title',
            field=models.CharField(blank=True, default='', help_text='An alternative title to use on pages with this category.', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='alternate_url',
            field=models.CharField(blank=True, help_text='An alternative URL to use instead of the one derived from the category hierarchy.', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_extra',
            field=models.TextField(blank=True, default='', help_text='(Advanced) Any additional HTML to be placed verbatim in the &lt;head&gt;'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', help_text='Comma-separated keywords for search engines.', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='uploads/categories/thumbnails'),
        ),
    ]
