# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-07 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_auto_20170426_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='article_set', to='categories.Category'),
        ),
    ]
