# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20170703_1041'),
        ('wiki', '0010_auto_20170707_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlerevision',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.MetadataRevision', verbose_name='metadata'),
        ),
    ]
