# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_articlerevision_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerevision',
            name='metadata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.MetadataRevision', verbose_name='metadata'),
        ),
    ]
