# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_auto_20170710_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlerevision',
            name='metadata',
        ),
    ]
