# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='animacy',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='counterpart',
        ),
    ]
