# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_adposition_adpositionrevision_example_usage_usagerevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerevision',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function', to='metadata.Supersense'),
        ),
        migrations.AddField(
            model_name='usagerevision',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='metadata.Supersense'),
        ),
    ]
