# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20170612_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supersense',
            fields=[
                ('metadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.Metadata')),
                ('animacy', models.DecimalField(decimal_places=0, max_digits=100)),
                ('counterpart', models.CharField(max_length=100)),
            ],
            bases=('metadata.metadata',),
        ),
    ]
