# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_auto_20170426_1727'),
        ('metadata', '0003_supersense'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.Article'),
        ),
    ]
