# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_remove_articlerevision_metadata'),
        ('metadata', '0004_remove_metadatarevision_articlerevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatarevision',
            name='articleRevision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.ArticleRevision'),
        ),
    ]
