# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-22 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20170622_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
