# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-12 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_metadatarevision_articlerevision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadatarevision',
            name='articleRevision',
        ),
    ]
