# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-22 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_auto_20170622_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supersense',
            name='animacy',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
