# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_auto_20170622_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supersense',
            name='counterpart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Supersense'),
        ),
    ]
