# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 23:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_auto_20170827_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='case_for',
            field=models.PositiveIntegerField(choices=[(1, 'none'), (2, 'pronominal'), (3, 'nominal')], default=0, verbose_name='Does the language have (affixal) case on nouns and pronouns, just pronouns, or neither?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagerevision',
            name='obj_case',
            field=models.PositiveIntegerField(choices=[(1, 'Unknown'), (2, 'Nominative'), (4, 'Accusative'), (8, 'Ergative'), (16, 'Absolutive'), (32, 'NominativeSOnly'), (64, 'Dative'), (128, 'Benefactive'), (256, 'Purposive'), (512, 'Genitive'), (1024, 'Relative'), (2048, 'Partitive'), (4096, 'Instrumental'), (8192, 'Comitative'), (16384, 'Vocative'), (32768, 'Comparative'), (65536, 'Equative'), (131072, 'Privative'), (262144, 'Proprietive'), (524288, 'Aversive'), (1048576, 'Formal'), (2097152, 'Translative'), (4194304, 'EssiveModal'), (8388608, 'Distal'), (16777216, 'Proximate'), (33554432, 'Essive'), (67108864, 'Allative'), (134217728, 'Ablative'), (268435456, 'Approximative'), (536870912, 'Terminative')], null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.CharField(help_text='Short (typically 2-character ISO) code for the language/dialect, such as <tt>en</tt> for English and <tt>en-us</tt> for American English.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]+(-?[a-z]+)*$', message='Language code should consist of lowercase ASCII strings separated by hyphens')]),
        ),
        migrations.AlterUniqueTogether(
            name='construal',
            unique_together=set([('role', 'function')]),
        ),
        migrations.AlterUniqueTogether(
            name='usagerevision',
            unique_together=set([('adposition', 'obj_case', 'construal')]),
        ),
    ]
