# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-13 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_auto_20171118_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='construal',
            options={'ordering': ['role', 'function'], 'verbose_name': 'construal'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'ordering': ['current_revision__metadatarevision__name'], 'verbose_name': 'metadata'},
        ),
        migrations.AlterModelOptions(
            name='usagerevision',
            options={'ordering': ['adposition', 'construal'], 'verbose_name': 'usage revision'},
        ),
        migrations.AddField(
            model_name='adpositionrevision',
            name='transliteration',
            field=models.CharField(blank=True, help_text='Romanization/phonemic spelling', max_length=200, verbose_name='Transliteration'),
        ),
        migrations.AlterUniqueTogether(
            name='usagerevision',
            unique_together=set([]),
        ),
    ]
