# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-13 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20170819_0708'),
        ('metadata', '0016_auto_20180613_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.DeleteModel(
            name='Corpus',
        ),
        migrations.DeleteModel(
            name='ExampleRevision',
        ),
        # migrations.RemoveField(
        #     model_name='corpus',
        #     name='metadata_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='examplerevision',
        #     name='metadatarevision_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='examplerevision',
        #     name='usage',
        # ),
    ]
