# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0017_auto_20180619_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpussentence',
            name='tokens',
            field=models.CharField(max_length=1000, null=True, verbose_name='Tokens'),
        ),
    ]
