# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0019_auto_20180724_1751'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usagerevision',
            unique_together=set([]),
        ),
    ]
