# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0020_auto_20180724_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='description',
            field=models.CharField(blank=True, help_text='Include number of tokens and basic statistics', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='metadatarevision',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
