# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-01 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0022_auto_20180701_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='simplemetadata_ptr',
        ),
        migrations.AddField(
            model_name='corpus',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
