# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-02 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0027_auto_20180701_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construal',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfs_with_function', to='metadata.Supersense'),
        ),
        migrations.AlterField(
            model_name='construal',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfs_with_role', to='metadata.Supersense'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='construal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptoken_with_construal', to='metadata.Construal'),
        ),
    ]
