# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-02 16:47
from __future__ import unicode_literals

from django.db import migrations
import wiki.plugins.metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0030_auto_20180701_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptokenannotation',
            name='mwe_subtokens',
            field=wiki.plugins.metadata.models.SeparatedValuesField(blank=True, max_length=200, verbose_name='MWE Subtokens'),
        ),
    ]
