# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-04 05:11
from __future__ import unicode_literals

from django.db import migrations
import wiki.plugins.metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0034_auto_20180703_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptokenannotation',
            name='main_subtoken_indices',
            field=wiki.plugins.metadata.models.IntListField(blank=True, max_length=200, null=True, verbose_name='Main Subtoken Indices'),
        ),
        migrations.AddField(
            model_name='ptokenannotation',
            name='main_subtoken_string',
            field=wiki.plugins.metadata.models.StringListField(blank=True, max_length=200, null=True, verbose_name='Main Subtoken String'),
        ),
    ]
