# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-21 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0037_auto_20180713_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpositionrevision',
            name='is_pp_idiom',
            field=models.CharField(blank=True, help_text='Lexicalized Adposition+Noun Phrase:\nsuch as "in no time", "to my surprise", but not "with exception of"', max_length=200, verbose_name='Is PP Idiom?'),
        ),
    ]
