# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-21 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0038_adpositionrevision_is_pp_idiom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpositionrevision',
            name='is_pp_idiom',
            field=models.BooleanField(default=False, help_text='Lexicalized Adposition+Noun Phrase:\nsuch as "in no time", "to my surprise", but not "with exception of"', verbose_name='Is PP Idiom?'),
        ),
    ]
