# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0039_auto_20180721_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatarevision',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
