# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 05:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20170819_0708'),
        ('metadata', '0003_auto_20170731_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMetadata',
            fields=[
                ('articleplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wiki.ArticlePlugin')),
            ],
            bases=('wiki.articleplugin',),
        ),
        migrations.CreateModel(
            name='Construal',
            fields=[
                ('simplemetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.SimpleMetadata')),
            ],
            options={
                'verbose_name': 'construal',
            },
            bases=('metadata.metadata',),
        ),
        migrations.CreateModel(
            name='ConstrualRevision',
            fields=[
                ('metadatarevision_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.MetadataRevision')),
            ],
            options={
                'verbose_name': 'construal revision',
            },
            bases=('metadata.metadatarevision',),
        ),
    ]
