# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adposition',
            fields=[
                ('metadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.Metadata')),
            ],
            options={
                'verbose_name': 'adposition',
            },
            bases=('metadata.metadata',),
        ),
        migrations.CreateModel(
            name='AdpositionRevision',
            fields=[
                ('metadatarevision_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.MetadataRevision')),
            ],
            options={
                'verbose_name': 'adposition revision',
            },
            bases=('metadata.metadatarevision',),
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exampleString', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('metadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.Metadata')),
            ],
            options={
                'verbose_name': 'usage',
            },
            bases=('metadata.metadata',),
        ),
        migrations.CreateModel(
            name='UsageRevision',
            fields=[
                ('metadatarevision_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.MetadataRevision')),
            ],
            options={
                'verbose_name': 'usage revision',
            },
            bases=('metadata.metadatarevision',),
        ),
    ]
