# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_metadatarevision_article_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatarevision',
            name='article_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_revision', to='wiki.ArticleRevision'),
        ),
    ]
