# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20170819_0708'),
        ('metadata', '0009_auto_20170820_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construalrevision',
            name='function',
        ),
        migrations.RemoveField(
            model_name='construalrevision',
            name='metadatarevision_ptr',
        ),
        migrations.RemoveField(
            model_name='construalrevision',
            name='role',
        ),
        migrations.DeleteModel(
            name='ConstrualRevision',
        ),
    ]
