# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20170821_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adposition',
            name='lang',
        ),
        migrations.AddField(
            model_name='adpositionrevision',
            name='lang',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='adpositions', to='metadata.Language', verbose_name='Language/dialect'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adpositionrevision',
            name='morphtype',
            field=models.PositiveIntegerField(choices=[(1, 'standalone preposition'), (2, 'standalone postposition'), (3, 'standalone circumposition'), (4, 'prefix'), (5, 'suffix'), (6, 'circumfix')], default=0, verbose_name='Morphological type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adpositionrevision',
            name='other_forms',
            field=models.CharField(blank=True, help_text='Exclude typos', max_length=200, verbose_name='Other spellings or inflections'),
        ),
        migrations.AddField(
            model_name='adpositionrevision',
            name='transitivity',
            field=models.PositiveIntegerField(choices=[(0, 'always intransitive'), (1, 'sometimes transitive'), (2, 'always transitive')], default=0),
            preserve_default=False,
        ),
    ]
