# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_auto_20170826_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpositionrevision',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adpositionrevisions', to='metadata.Language', verbose_name='Language/dialect'),
        ),
    ]
