# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 23:47
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_auto_20171118_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpositionrevision',
            name='obj_cases',
            field=bitfield.models.BitField([('Unknown', 'Unknown'), ('Nominative', 'Nominative'), ('Accusative', 'Accusative'), ('Ergative', 'Ergative'), ('Absolutive', 'Absolutive'), ('NominativeSOnly', 'NominativeSOnly'), ('Dative', 'Dative'), ('Benefactive', 'Benefactive'), ('Purposive', 'Purposive'), ('Genitive', 'Genitive'), ('Relative', 'Relative'), ('Partitive', 'Partitive'), ('Instrumental', 'Instrumental'), ('Comitative', 'Comitative'), ('Vocative', 'Vocative'), ('Comparative', 'Comparative'), ('Equative', 'Equative'), ('Privative', 'Privative'), ('Proprietive', 'Proprietive'), ('Aversive', 'Aversive'), ('Formal', 'Formal'), ('Translative', 'Translative'), ('EssiveModal', 'EssiveModal'), ('Distal', 'Distal'), ('Proximate', 'Proximate'), ('Essive', 'Essive'), ('Allative', 'Allative'), ('Ablative', 'Ablative'), ('Approximative', 'Approximative'), ('Terminative', 'Terminative')], default=None, verbose_name='Possible cases of the object'),
        ),
        migrations.AddField(
            model_name='language',
            name='cases',
            field=bitfield.models.BitField([('Unknown', 'Unknown'), ('Nominative', 'Nominative'), ('Accusative', 'Accusative'), ('Ergative', 'Ergative'), ('Absolutive', 'Absolutive'), ('NominativeSOnly', 'NominativeSOnly'), ('Dative', 'Dative'), ('Benefactive', 'Benefactive'), ('Purposive', 'Purposive'), ('Genitive', 'Genitive'), ('Relative', 'Relative'), ('Partitive', 'Partitive'), ('Instrumental', 'Instrumental'), ('Comitative', 'Comitative'), ('Vocative', 'Vocative'), ('Comparative', 'Comparative'), ('Equative', 'Equative'), ('Privative', 'Privative'), ('Proprietive', 'Proprietive'), ('Aversive', 'Aversive'), ('Formal', 'Formal'), ('Translative', 'Translative'), ('EssiveModal', 'EssiveModal'), ('Distal', 'Distal'), ('Proximate', 'Proximate'), ('Essive', 'Essive'), ('Allative', 'Allative'), ('Ablative', 'Ablative'), ('Approximative', 'Approximative'), ('Terminative', 'Terminative')], default=None, verbose_name='All cases present in the language'),
        ),
        migrations.AddField(
            model_name='language',
            name='pobj_cases',
            field=bitfield.models.BitField([('Unknown', 'Unknown'), ('Nominative', 'Nominative'), ('Accusative', 'Accusative'), ('Ergative', 'Ergative'), ('Absolutive', 'Absolutive'), ('NominativeSOnly', 'NominativeSOnly'), ('Dative', 'Dative'), ('Benefactive', 'Benefactive'), ('Purposive', 'Purposive'), ('Genitive', 'Genitive'), ('Relative', 'Relative'), ('Partitive', 'Partitive'), ('Instrumental', 'Instrumental'), ('Comitative', 'Comitative'), ('Vocative', 'Vocative'), ('Comparative', 'Comparative'), ('Equative', 'Equative'), ('Privative', 'Privative'), ('Proprietive', 'Proprietive'), ('Aversive', 'Aversive'), ('Formal', 'Formal'), ('Translative', 'Translative'), ('EssiveModal', 'EssiveModal'), ('Distal', 'Distal'), ('Proximate', 'Proximate'), ('Essive', 'Essive'), ('Allative', 'Allative'), ('Ablative', 'Ablative'), ('Approximative', 'Approximative'), ('Terminative', 'Terminative')], default=None, verbose_name='All cases that ever apply to an adpositional object'),
        ),
    ]
