# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-21 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0019_auto_20180620_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptokenannotation',
            name='is_transitive',
            field=models.BooleanField(default=True, help_text='Does the adposition take an object?', verbose_name='Transitive?'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='is_gold',
            field=models.BooleanField(default=False, verbose_name='Gold Annotation?'),
        ),
    ]
