# Generated by Django 2.2.4 on 2019-10-15 03:41

from django.db import migrations, models
import django.db.models.deletion
import wiki.plugins.metadata.models


class Migration(migrations.Migration):

    replaces = [('metadata', '0021_auto_20180701_1338'), ('metadata', '0022_auto_20180701_1339'), ('metadata', '0023_auto_20180701_1347'), ('metadata', '0024_auto_20180701_1429'), ('metadata', '0025_auto_20180701_1432'), ('metadata', '0026_auto_20180701_1913'), ('metadata', '0027_auto_20180701_1951'), ('metadata', '0028_auto_20180701_2234'), ('metadata', '0029_auto_20180701_2252'), ('metadata', '0030_auto_20180701_2314'), ('metadata', '0031_ptokenannotation_mwe_subtokens'), ('metadata', '0032_auto_20180702_1546'), ('metadata', '0033_auto_20180703_1308'), ('metadata', '0034_auto_20180703_1525'), ('metadata', '0035_auto_20180704_0111')]

    dependencies = [
        ('metadata', '0020_auto_20180621_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='id',
        ),
        migrations.AddField(
            model_name='ptokenannotation',
            name='is_abbr',
            field=models.BooleanField(default=False, verbose_name='Abbreviation?'),
        ),
        migrations.AddField(
            model_name='ptokenannotation',
            name='is_typo',
            field=models.BooleanField(default=False, verbose_name='Typo?'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='adposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Adposition'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='construal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Construal'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='gov_head',
            field=models.CharField(max_length=200, null=True, verbose_name='Governor Head'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='gov_obj_syntax',
            field=models.CharField(max_length=200, null=True, verbose_name='Governor-Object Syntax'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='obj_head',
            field=models.CharField(max_length=200, null=True, verbose_name='Object Head'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.CorpusSentence'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Usage'),
        ),
        migrations.AddField(
            model_name='ptokenannotation',
            name='gov_head_index',
            field=models.PositiveIntegerField(null=True, verbose_name='Governor Index'),
        ),
        migrations.AddField(
            model_name='ptokenannotation',
            name='obj_head_index',
            field=models.PositiveIntegerField(null=True, verbose_name='Object Index'),
        ),
        migrations.AlterField(
            model_name='corpussentence',
            name='tokens',
            field=wiki.plugins.metadata.models.SeparatedValuesField(max_length=1000, null=True, verbose_name='Tokens'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='token_indices',
            field=wiki.plugins.metadata.models.SeparatedValuesField(blank=True, max_length=200, verbose_name='Token Indices'),
        ),
        migrations.AlterField(
            model_name='corpussentence',
            name='word_gloss',
            field=wiki.plugins.metadata.models.SeparatedValuesField(blank=True, max_length=200, verbose_name='Word Gloss'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='simplemetadata_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.SimpleMetadata'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='construal',
            options={'ordering': ['role', 'function', 'special'], 'verbose_name': 'construal'},
        ),
        migrations.AddField(
            model_name='construal',
            name='special',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='construal',
            unique_together={('role', 'function', 'special')},
        ),
        migrations.AlterField(
            model_name='construal',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfs_with_function', to='metadata.Supersense'),
        ),
        migrations.AlterField(
            model_name='construal',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfs_with_role', to='metadata.Supersense'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='construal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptoken_with_construal', to='metadata.Construal'),
        ),
        migrations.AlterField(
            model_name='construal',
            name='special',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='adposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Adposition'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='construal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptoken_with_construal', to='metadata.Construal'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Usage'),
        ),
        migrations.AlterField(
            model_name='adpositionrevision',
            name='other_forms',
            field=wiki.plugins.metadata.models.SeparatedValuesField(blank=True, help_text='Exclude typos, Separate by spaces', max_length=200, verbose_name='Other spellings or inflections'),
        ),
        migrations.AlterField(
            model_name='adpositionrevision',
            name='other_forms',
            field=wiki.plugins.metadata.models.SeparatedValuesField(blank=True, help_text='Exclude typos, Separate by spaces', max_length=200, null=True, verbose_name='Other spellings or inflections'),
        ),
        migrations.AlterField(
            model_name='adpositionrevision',
            name='other_forms',
            field=wiki.plugins.metadata.models.StringListField(blank=True, help_text='Exclude typos, Separate by spaces', max_length=200, null=True, verbose_name='Other spellings or inflections'),
        ),
        migrations.AlterField(
            model_name='corpussentence',
            name='tokens',
            field=wiki.plugins.metadata.models.StringListField(max_length=1000, null=True, verbose_name='Tokens'),
        ),
        migrations.AlterField(
            model_name='corpussentence',
            name='word_gloss',
            field=wiki.plugins.metadata.models.StringListField(blank=True, max_length=200, verbose_name='Word Gloss'),
        ),
        migrations.AddField(
            model_name='ptokenannotation',
            name='mwe_subtokens',
            field=wiki.plugins.metadata.models.StringListField(blank=True, max_length=200, verbose_name='MWE Subtokens'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='token_indices',
            field=wiki.plugins.metadata.models.IntListField(blank=True, max_length=200, verbose_name='Token Indices'),
        ),
        migrations.AddField(
            model_name='ptokenannotation',
            name='main_subtoken_indices',
            field=wiki.plugins.metadata.models.IntListField(blank=True, max_length=200, null=True, verbose_name='Main Subtoken Indices'),
        ),
        migrations.AddField(
            model_name='ptokenannotation',
            name='main_subtoken_string',
            field=wiki.plugins.metadata.models.StringListField(blank=True, max_length=200, null=True, verbose_name='Main Subtoken String'),
        ),
    ]
