# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-01 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0021_auto_20180701_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptokenannotation',
            name='gov_head_index',
            field=models.PositiveIntegerField(null=True, verbose_name='Governor Index'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='obj_head_index',
            field=models.PositiveIntegerField(null=True, verbose_name='Object Index'),
        ),
    ]
