# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-01 18:29
from __future__ import unicode_literals

from django.db import migrations
import wiki.plugins.metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0023_auto_20180701_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpussentence',
            name='tokens',
            field=wiki.plugins.metadata.models.SeparatedValuesField(max_length=1000, null=True, verbose_name='Tokens'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='token_indices',
            field=wiki.plugins.metadata.models.SeparatedValuesField(blank=True, max_length=200, verbose_name='Token Indices'),
        ),
    ]
