# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-01 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0026_auto_20180701_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='construal',
            options={'ordering': ['role', 'function', 'special'], 'verbose_name': 'construal'},
        ),
        migrations.AddField(
            model_name='construal',
            name='special',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='construal',
            unique_together=set([('role', 'function', 'special')]),
        ),
    ]
