# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-02 19:46
from __future__ import unicode_literals

from django.db import migrations
import wiki.plugins.metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0031_ptokenannotation_mwe_subtokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpositionrevision',
            name='other_forms',
            field=wiki.plugins.metadata.models.SeparatedValuesField(blank=True, help_text='Exclude typos, Separate by spaces', max_length=200, verbose_name='Other spellings or inflections'),
        ),
    ]
