# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-03 17:08
from __future__ import unicode_literals

from django.db import migrations
import wiki.plugins.metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0032_auto_20180702_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpositionrevision',
            name='other_forms',
            field=wiki.plugins.metadata.models.SeparatedValuesField(blank=True, help_text='Exclude typos, Separate by spaces', max_length=200, null=True, verbose_name='Other spellings or inflections'),
        ),
    ]
