# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-03 19:25
from __future__ import unicode_literals

from django.db import migrations
import wiki.plugins.metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0033_auto_20180703_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpositionrevision',
            name='other_forms',
            field=wiki.plugins.metadata.models.StringListField(blank=True, help_text='Exclude typos, Separate by spaces', max_length=200, null=True, verbose_name='Other spellings or inflections'),
        ),
        migrations.AlterField(
            model_name='corpussentence',
            name='tokens',
            field=wiki.plugins.metadata.models.StringListField(max_length=1000, null=True, verbose_name='Tokens'),
        ),
        migrations.AlterField(
            model_name='corpussentence',
            name='word_gloss',
            field=wiki.plugins.metadata.models.StringListField(blank=True, max_length=200, verbose_name='Word Gloss'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='mwe_subtokens',
            field=wiki.plugins.metadata.models.StringListField(blank=True, max_length=200, verbose_name='MWE Subtokens'),
        ),
        migrations.AlterField(
            model_name='ptokenannotation',
            name='token_indices',
            field=wiki.plugins.metadata.models.IntListField(blank=True, max_length=200, verbose_name='Token Indices'),
        ),
    ]
