# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-10 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0035_auto_20180704_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='description',
            field=models.CharField(blank=True, help_text='Include number of tokens and basic statistics', max_length=300, verbose_name='Description'),
        ),
    ]
