# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-14 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import wiki.plugins.metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0036_auto_20180710_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='version',
            field=models.CharField(max_length=200, null=True, validators=[wiki.plugins.metadata.models.version_validator], verbose_name='Version'),
        ),
    ]
