# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 19:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_remove_category'),
        ('metadata', '0042_auto_20180728_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Language',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='categories.ArticleCategory')
        ),
        migrations.AlterField(
            model_name='Supersense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='categories.ArticleCategory')
        ),
    ]
