# Generated by Django 2.2.4 on 2019-12-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0044_auto_20191014_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersenserevision',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supersenserevision',
            name='deprecation_message',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
