# Generated by Django 2.2.13 on 2020-08-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0046_corpus_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='deprecated',
            field=models.BooleanField(default=False, verbose_name='Is this a deprecated version of a corpus?'),
        ),
    ]
