# Generated by Django 3.1.14 on 2022-08-12 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0047_auto_20210304_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParallelSentenceAlignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_sentence', to='metadata.corpussentence')),
                ('target_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_sentence', to='metadata.corpussentence')),
            ],
            options={
                'verbose_name': 'parallel sentence alignment',
                'ordering': ['id'],
                'unique_together': {('source_sentence', 'target_sentence')},
            },
        ),
    ]
