# Generated by Django 3.1.14 on 2022-08-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0048_parallelsentencealignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParallelPTokenAlignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_example', to='metadata.ptokenannotation')),
                ('target_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_example', to='metadata.ptokenannotation')),
            ],
            options={
                'verbose_name': 'adposition alignment',
                'ordering': ['id'],
                'unique_together': {('source_example', 'target_example')},
            },
        ),
    ]
